### ISSUE TITLE
Small typo in the Readme

### ISSUE THREAD

**Issue by RGDub** [adgressus/The-GDub-Special#1]
There's a type in the instructions in the readme. The command to download Terraform is written as "Brew Install Terrafrom" rather than "brew install terraform".

**Comment by RGDub** [comment]
Same issue for the init command

**Comment by adgressus** [comment]
Sorry brother, but can't replicate this. If you're still seeing capitalization in the readme, let me know what you're using to display the file. That will help me replicate the isse.
